### ISSUE TITLE
Booking payment idempotency key

### ISSUE THREAD

**Issue by JElgar** [BristolSTA/uobtheatre-api#126]
Currently, booking payments use the booking id as the idempotency key. This probably means we can't have more than 1 payment per booking. This will become a problem in the future. It's worth investigating what impact this has i.e. does it affect refunds or just multiple payments or nothing.

**Comment by atoff** [comment]
This has been fixed for the SQUARE_ONLINE provider. However, SQUARE_POS idempotency key is set by the API. This should probably also be offloaded to the frontend. Closing, but will make a note for this to be used in https://github.com/BristolSTA/uobtheatre-api/pull/299
