### ISSUE TITLE
Draft Booking reserves tickets foreverr

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-api#180]
When tickets are added to a booking, they are no longer available to other users to be booked. This has no expiration so any tickets added to a booking are permanently reserved.

- We should add an expiration to a draft booking
- If the current datetime is after the expiration then the tickets should be re-available to book
- If a booking has been resumed and the tickets are no longer available they should be removed and a warning should be returned

**Comment by JElgar** [comment]
We will need to decide whether a draft can be refreshed (i.e. someone can ask for more time), or if a draft is extended every time a ticket is added or something.

@atoff @streth11 @walkerkit opinions?

**Comment by atoff** [comment]
The way most places seem to do this is that the booking is valid for 15 mins or so from its creation - it doesn't renew when you change it, etc. We could make it that it's 15 mins from the last activity on the booking, which would also be a valid choice. Down to preference in the end

**Comment by JElgar** [comment]
@atoff are this and #195 the same issue? If so can we close one?
