### ISSUE TITLE
Performance: Reserved Tickets

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-api#195]
Once a user creates a booking (via web), the tickets in the booking are automatically reserved (perhaps even marked as sold!)

- There should be a distinction between a sold ticket and a reserved ticket. (Need to check the functions on the performance model to ensure we don't do tickets_sold = paid tickets + reserved tickets)
- Draft bookings should have a time limit (usually a user has 15 mins or so from starting the booking to complete the purchase before they must start again)
- There should be a way for the front end to see the time remaining to complete a booking.
- Maybe this booking time limit should be removable for box office staff or similar?
- Should there be a maximum of reserved tickets (e.g. a user creates a booking on the web and selects the maximum permitted number of tickets. This would result in no one being able to purchase tickets!)
- If the current datetime is after the expiration then the tickets should be re-available to book
- If a booking has been resumed and the tickets are no longer available they should be removed and a warning should be returned

**Comment by JElgar** [comment]
I've opened #234 which should be slightly clearer from an API perspective
