### ISSUE TITLE
discount requirements unique to a specific performance

### ISSUE THREAD

**Issue by streth11** [BristolSTA/uobtheatre-api#211]

**Comment by JElgar** [comment]
Can you clarify what you mean here @streth11 ? From what I understand:
- discount requirements are part of a discount
- performances have many discounts

Are we missing some required functionality or is something above wrong/broken?

**Comment by streth11** [comment]
unless this , was modified previously, basically:

For example, if one show wants a student discount at 20% but another show wants a student discount at 30%, we cannot create this due to the uniqueness requirements on discounts.
