### ISSUE TITLE
discounted_price() IS SLOWWWWWWWW

### ISSUE THREAD

**Issue by streth11** [BristolSTA/uobtheatre-api#213]
it has been proven that the api runs the function discounted_price() on a given booking 9n times for n tickets of the same concession type and same seatgroup when adding tickets.

This doesnt sound good gang :(((

**Comment by JElgar** [comment]
Is this true: "it has been proven that the api runs the function discounted_price() on a given booking 9n times for n tickets of the same concession type and same seatgroup when adding tickets."?

**Comment by streth11** [comment]
james i wish i took a screenshot of the logs, but toff can probably be my citation as he was there at the time of my discovery

**Comment by streth11** [comment]
alex said stuff about making things like subtotal a '@cached_property' or similar so it doesn't have to be worked out multiple times for one graphql call
