### ISSUE TITLE
Society slug not found error

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-api#235]
When calling the society query with an unknown/invalid slug, instead of just returning null, an exception is thrown

**Comment by streth11** [comment]
![image](https://user-images.githubusercontent.com/61627133/132094982-91ab386f-6c9f-4fbd-9030-b1d78e5ebb03.png)

seems to be fine.. has this been fixed elsewhere and issue left open?

**Comment by atoff** [comment]
This is an issue with societies, not productions

**Comment by streth11** [comment]
ahh

**Comment by streth11** [comment]
![image](https://user-images.githubusercontent.com/61627133/132324651-ee76194b-3ce9-4bb8-bda7-244ece018271.png)

**Comment by streth11** [comment]
am im missing something here

**Comment by streth11** [comment]
can you check if this also exists with venues, i would believe it do
