### ISSUE TITLE
Production Sales Breakdown (and breakdown permissions)

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-api#246]
Expanding on the sales breakdown started in the reports branch the following should be available on a production:
- Total number of tickets sold across performances
- Sum of the total capacity across performances (i.e. the total capacity of the production)
- Sum the number of bookings for a performance
- Have a breakdown of sales by concession type for a performance
- Query the total sales income for the production (this is, the sum of booking payments - positive and negative - deducting any misc costs). This should also be available on a performance basis on a performance node. Must be restricted to authorised users

We should also check that these sensitive sales numbers (such as total capacities and the like) are only available to people with adequate permissions. We don't want regular end users to be able to work out detailed sales information if they inspect our queries / create their own queries.

**Comment by JElgar** [comment]
Blocked by #236
