### ISSUE TITLE
Accessibility requirements during booking

### ISSUE THREAD

**Issue by JElgar** [BristolSTA/uobtheatre-api#34]
Brief: Allow customers to provide details of accessibility requirements (such as limited mobility, wheelchair access, etc) when completing a booking

Requirements:
- Ability for submission of accessibility details (text field) on a booking model, which can be nullable
- On confirmation and payment of the booking, if accessibility details have been provided, email: 1) the contact_email associated with the production and 2) people who have the "view_bookings" permission on the production. We should email them details about their booking, along with the details that they provided us.

**Comment by atoff** [comment]
@Guidedriver0 I think this could be a good thing for you to look at after your current PR is completed. There is already a PR with some of this done at https://github.com/BristolSTA/uobtheatre-api/pull/518, but feel free to start from scratch if you'd like. Take a look / think and let me or @JElgar know if you have any questions!
