### ISSUE TITLE
GraphQL Inconsistencies

### ISSUE THREAD

**Issue by atoff** [BristolSTA/uobtheatre-api#65]
The following fields are not present on their respective GraphQL nodes:

**PerformanceNode**
- [x] `isInperson: Boolean!`
- [x] `isOnline: Boolean!`
- [x] `durationMins: Int!`
- [x] `soldOut: Boolean!`
- [x] `discounts: [DiscountNode]`
- [x] warnings not required

**BookingNode**
- [x] `tickets: [TicketNode]!`
- [x] `user: UserNode`

**PriceBreakdownNode**
- [x] All of the Int's should be !
- [x] `ticketsDiscountedPrice: Int!`

**PriceBreakdownTicketNode**

- [x] missing ID! feild

**CrewRoleNode**
- [ ] Department should return a human-friendly string rather than an enum

- [ ] General Enum FIxes

### Queries

- [x] Need a `production` (singular) query to get a single production
- [x] Need ability to select productions which are in the future, and ability to order by (i.e. get 10 most upcoming productions)
- [x] `venue` (singular) query? If not, need ability to select `venues` with a slug. Selecting with a name seems a bit pointless

More to be added as I find them...

**Comment by streth11** [comment]
this will get a single production - is this ok.
`{
  productions (slug: "example-show") {
    edges {
      node {
        id
        name
        slug
      }
    }
  }
}`
same applied to venue

**Comment by JElgar** [comment]
`minTicketPrice` => `minSeatPrice`

**Comment by streth11** [comment]
see branch fix/graphql-inconsistensies
